name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Slash Command Dispatch
        uses: tradingassistant-net/actions/github/slash-command-dispatch@0.12.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: tradingassistant-net/actions
          commands: rebuild-readme, terraform-fmt
          permission: none
          issue-type: pull-request
